server:
  port: 6542


spring:
  application:
    name: websocket-chatroom
  mvc:
    view:
      suffix: .html
      prefix: /html/


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/im-learn?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai

    username: root
    password: 123

  redis:
    host: ip
    port: 6379
    password: 123
    database: 4

